name: model_test_train

permissions:
  id-token:  write
  contents: write

on:
  - push

jobs:
  run:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - uses: actions/setup-python@v4
      - uses: iterative/setup-cml@v1

      # - name: install dependices
      #   run: 
      #     pip install -r requirements.txt
      
      - name: test model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          python test.py

      - name: train model
        run: |
          python train_model.py

      - name: create the report file
        run: |
          echo " model training complete accuracy: 92%" > report.md
